language: php

php:
  - '7.0'

services:
  - mysql

env:
  - DATABASE_NAME=orangesolution DATABASE_USER=travis DATABASE_PASS=

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install

script:
  - mysql < install/database.sql
  - find application config install public route -maxdepth 100 -iname \*.php -type f -exec php -l {} \;
